### ISSUE TITLE
unannotated figures

### ISSUE THREAD

**Issue by vick2075** [b96young/ballisticsolver#1]
Hi,

With regard to line 100 in BallisticCalculationClass.py: 

drag_coefficient = bullet_mass*reference_cd/self.bullet["ballistic_coeff"]/math.pow(bullet_dia,2)*0.0014223

What is the last figure about (0.0014223)?

**Comment by b96young** [comment]
The calculator works in SI units. Typically the BC tables use imperial. The 0.0014223 comes from the conversion from BC units in lbs/in^2 to kg/m^2.

lbf / in^2 * (0.454kg / lbf) * (in^2 / (0.0254*m)^2) = 703 kg/m^2

Since BC appears on the denominator, the conversion factor is inverted.

1 / 703 = 0.0014223

**Comment by vick2075** [comment]
But why would you multiply the reciprocal BC with the rest of the factors in the drag_coeff formula?

**Comment by b96young** [comment]
You could implement it either way:

drag_coefficient = bullet_mass*reference_cd/self.bullet["ballistic_coeff"]/math.pow(bullet_dia,2)*0.0014223

or

drag_coefficient = bullet_mass*reference_cd/(self.bullet["ballistic_coeff"]*703 * math.pow(bullet_dia,2))

**Comment by vick2075** [comment]
I don't understand how you are declaring your drag coeff (Cd) for subsequent trajectory calculation. For example, in your online ballistic cal, you used: 1/8 * pi * Cd_ref / BC * air density (rho) which is good.

However, here you are using Cd_projectile = m * Cd_ref / BC / caliber ^2 which is all fine. However I was expecting the following:
Cd_projectile * (rho * A) / (2*m) to have the same result as in your online ballistic cal as mentioned above!!
where A = cross sectional Area of bullet

**Comment by b96young** [comment]
They should have the same result as they are the same equation, only the first one has been simplified further. 

For the first equation, you need to use the reference drag value (Cd_ref) for the given velocity in the acceleration formula. In the second form, we calculate the actual Cd value (Cd_projectile) and then use the standard aerodynamic drag formula.

**Comment by vick2075** [comment]
Which is the same thing: 0.5 * rho * Cd_proj * A / m = Cd_proj * (rho *A) / (2*m)

So why are you using 1/703 ? I still don't understand this bit!!

**Comment by b96young** [comment]
Maybe this clears is up, on the online-ballistic-calculator, the BC is converted where it is defined (Line 73). In ballisticsolver, it is converted in the calculation.

**Comment by vick2075** [comment]
Okay! I think I understand but you need to confirm. Is the input of BC in lbs/in^2? And this is just a conversion? Because initially I thought all your input was in the metric system!

**Comment by b96young** [comment]
Yes, all the charts for BC you get online are usually lbf/in^2. I prefer to work in metric, so all the calculations within the program are using metric units. It is just a conversion factor.

**Comment by vick2075** [comment]
Okay thanks a lot!
